var fs = require('fs')

var buffer = fs.readFileSync('./ucs.json','utf8')

var ucs = JSON.parse(buffer)

//insere Ucs
ucs.forEach(u => {
    var string = '\n###  http://www.semanticweb.org/antóniocarvalho/ontologies/prc2021/uc#' + u.id + '\n' + ':' + u.id + ' ' + 'rdf:type owl:NamedIndividual' + ' ,' + '\n'
    + '\t\t\t ' + ':UnidadeCurricular ;' + '\n' + '\t' + ':anoLetivo ' + u.anoLetivo + ' ;' + '\n' + '\t' + ':designacao "' + u.designação +'" .' + '\n\n'
    fs.appendFileSync('ontologia.ttl', string, function(err){
    if (err) console.log(err)
})
})

var buffer1 = fs.readFileSync('./docentes.json','utf8')

var docentes = JSON.parse(buffer1);

//insere docentes
docentes.forEach(d => {
    var string = '\n###  http://www.semanticweb.org/antóniocarvalho/ontologies/prc2021/uc#' + d.id + '\n' + ':' + d.id + ' ' + 'rdf:type owl:NamedIndividual' + ' ;' + '\n'
    + '\t' + ':ensina' + ' :' + d.unidadeCurricular + ' ;' + '\n' +  '\t' + ':nome "' +d.nome + '"  .' + '\n\n'
    fs.appendFileSync('ontologia.ttl', string, function(err){
    if (err) console.log(err)
})
})

var buffer2 = fs.readFileSync('./alunos.json','utf8')

var alunos = JSON.parse(buffer2);

//insere alunos
alunos.forEach(a => {
    var string = '\n###  http://www.semanticweb.org/antóniocarvalho/ontologies/prc2021/uc#' + a.id + '\n' + ':' + a.id + ' ' + 'rdf:type owl:NamedIndividual' + ' ;' + '\n'
    + '\t' + ':frequenta' + ' :' + a.unidadeCurricular + ' ;' + '\n' +  '\t' + ':nome "' +a.nome + '"  .' + '\n\n'
    fs.appendFileSync('ontologia.ttl', string, function(err){
    if (err) console.log(err)
})
})







// ###  Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi